### ISSUE TITLE
kronos setup help

### ISSUE THREAD

**Issue by xtmgah** [jtaghiyar/kronos#2]
Hello:

I am doing everything to run the titan_workflow pipeline, but still, they are always failed because of the chromosoem setup in titan_setup.txt file. 

The software suggest the following setup: 

**SHARED**  chromosomes  ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X','Y']

However, in the script of TASK3 and TASK4, the script will show error information of "no chromosome of ['1'. I think the pipeline take the "[" to the command... So, is there any way to fix this? 

I try the following setup, but it will failed in the very begin of kronos pipeline...
**SHARED**  chromosomes "'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X','Y'"

I also try the following setup, 
**SHARED**  chromosomes '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X

but it failed as the following information: 

```
TCGA-KL_titantest pipeline failed due to error: <class 'ruffus.ruffus_exceptions.RethrownJobError'>, 



Original exception:

    Exception #1
      'exceptions.Exception(Chromosomes should be list)' raised in ...
       Task = def run_titan___TASK_6__0__function(...):
       Job  = [run_titan, __TASK_6__0_, [__TASK_2__, __TASK_5__]]

    Traceback (most recent call last):
      File "/home/zhangt8/.local/lib/python2.7/site-packages/ruffus/task.py", line 685, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/home/zhangt8/.local/lib/python2.7/site-packages/ruffus/task.py", line 486, in job_wrapper_generic
        return user_defined_work_func(*param)
      File "/home/zhangt8/.local/lib/python2.7/site-packages/kronos/logger.py", line 188, in wrapper
        res = func(*args, **kwargs)
      File "/home/zhangt8/.local/lib/python2.7/site-packages/kronos/logger.py", line 154, in wrapper
        res = func(*args, **kwargs)
      File "titan_init/intermediate_pipeline_scripts/TCGA-KL_titantest.py", line 1122, in run_titan___TASK_6__0__function
        run_script = rm.generate_script(__TASK_6__0__task, "{'num_clusters':1, 'ploidy':2}", None)
      File "/home/zhangt8/.local/lib/python2.7/site-packages/kronos/run_manager.py", line 113, in generate_script
        cmd, cmd_args = component.make_cmd(chunk)
      File "/home/zhangt8/software/TITAN/titan_workflow/components/run_titan/component_main.py", line 37, in make_cmd
        raise Exception('Chromosomes should be list')
    Exception: Chromosomes should be list


denied: job "5086112" does not exist
denied: job "5086113" does not exist
denied: job "5087030" does not exist
denied: job "5087520" does not exist
denied: job "5088256" does not exist
denied: job "5088269" does not exist
denied: job "5088270" does not exist
denied: job "5088271" does not exist
denied: job "5088294" does not exist
denied: job "5088301" does not exist
denied: job "5090806" does not exist
denied: job "5090807" does not exist
denied: job "5091809" does not exist
denied: job "5091813" does not exist
denied: job "5092818" does not exist
denied: job "5092828" does not exist
denied: job "5092832" does not exist
denied: job "5092833" does not exist
denied: job "5092835" does not exist
denied: job "5092836" does not exist
denied: job "5092837" does not exist
denied: job "5092838" does not exist
denied: job "5092839" does not exist
denied: job "5092840" does not exist
denied: job "5092841" does not exist
denied: job "5092842" does not exist
denied: job "5092843" does not exist
denied: job "5092844" does not exist
denied: job "5092845" does not exist
TCGA-KL_titantest pipeline finished with exit code -1
    Job completed
Completed Task = task_0
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
```

Please help me this? thanks so much...,.

**Comment by jtaghiyar** [comment]
Hi xtmgah,
This issue is not related to Kronos per se. Please use the [repo](https://github.com/MO-BCCRC/titan_workflow/issues) of titan_workflow to report the issue. I'll try to get someone to help you with it once you created the ticket over there. I'll close this ticket here. Thanks.
